INSERT INTO employee
    (first_name, last_name, id)
VALUES
    ('Tom', 'Nook', 1),
    ('Isabelle', 'Dog', 2),
    ('Celeste', 'Owl', 3),
    ('Flick', 'Chameleon', 4),
    ('Wilbur', 'Dodo', 5),
    ('Timmy', 'Nook', 6),
    ('Tommy', 'Nook', 7),
    ('Brewster', 'Pigeon', 8),
    ('Digby', 'Dog', 9),
    ('Rosie', 'Cat', 10),
    ('Daisy', 'Dog', 11),
    ('Mabel', 'Hedgehog', 12),
    ('Sable', 'Hedgehog', 13),
    ('Label', 'Hedgehog', 14),
    ('Orville', 'Dodo', 15),
    ('Blathers', 'Owl', 16);